version: '3.7'

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backup:
    image: amazonlinux:2
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./control/backup.sh:/backup.sh
    environment:
      PGDATA: /var/lib/postgresql/data
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      BUCKET_NAME: ${BUCKET_NAME}
    entrypoint: /backup.sh

volumes:
  pgdata:
